# RNAscope Reanalysis

Batch reanalyse saved RNAscope ROI JSON files from the NWB session folders, save new reanalysis JSON files, and compare the reconstructed counts with the experimenter counts stored in each NWB file.

In [1]:
from pathlib import Path
import os
import json
import re
import sys

import pandas as pd
from IPython.display import display, Markdown
from pynwb import NWBHDF5IO

repo = Path(os.environ.get(
    "ANALYSIS_ROOT",
    Path.home() / "Documents" / "Repositories" / "analysis_Belal2026"
))
functions_dir = repo / "Python functions"

if str(functions_dir) not in sys.path:
    sys.path.insert(0, str(functions_dir))

from master_RNAscope import (
    RNAscopeAnalysisFinish,
    reconstruct_state_from_saved_analysis,
    save_rnascope_field_analysis,
    parse_field_metadata,
    counts_from_roi_jsons,
)

nwb_root = repo / "NWBdata" / "001832"

sessions = ["sub-L1-ST8_ses-20240905T115902", 
            "sub-L2-ST8_ses-20240909T100245", 
            "sub-L3-ST6_ses-20240909T112846", 
            "sub-L4-ST8_ses-20240916T101347"]

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

display(Markdown(f"NWB root: `{nwb_root}`"))

NWB root: `/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832`

In [2]:
# Reanalysis Settings

run_reanalysis = True
save_reanalysis = True
source_analysis_folder = "analysis"
reanalysis_folder = "reanalysis"
display_mode = "rendered_from_raw"

detection_method = "DoG"
dog_mode = "tolerance"

if detection_method == "DoG":
    new_params = {
        "detection_method": detection_method,
        "dog_mode": dog_mode,
        "sigma_small": 1.0,
        "sigma_large": 2.8,
        "threshold_percentile": 99,
        "peak_footprint": 4,
        "maxima_tolerance": 170,
        "show_detected": False,
        "show_verify": False,
    }
else:
    new_params = {
        "detection_method": detection_method,
        "maxima_tolerance": 160,
        "show_detected": False,
        "show_verify": False,
    }
    
new_params

{'detection_method': 'DoG',
 'dog_mode': 'tolerance',
 'sigma_small': 1.0,
 'sigma_large': 2.8,
 'threshold_percentile': 99,
 'peak_footprint': 4,
 'maxima_tolerance': 170,
 'show_detected': False,
 'show_verify': False}

In [3]:
# Check Inputs
input_rows = []

session_paths = {
    "L1.ST8": {
        "session_root": nwb_root / "sub-L1-ST8",
        "nwb_path": nwb_root / "sub-L1-ST8" / "sub-L1-ST8_ses-20240905T115902.nwb",
    },
    "L2.ST8": {
        "session_root": nwb_root / "sub-L2-ST8",
        "nwb_path": nwb_root / "sub-L2-ST8" / "sub-L2-ST8_ses-20240909T100245.nwb",
    },
    "L3.ST6": {
        "session_root": nwb_root / "sub-L3-ST6",
        "nwb_path": nwb_root / "sub-L3-ST6" / "sub-L3-ST6_ses-20240909T112846.nwb",
    },
    "L4.ST8": {
        "session_root": nwb_root / "sub-L4-ST8",
        "nwb_path": nwb_root / "sub-L4-ST8" / "sub-L4-ST8_ses-20240916T101347.nwb",
    },
}

for session, paths in session_paths.items():
    session_root = paths["session_root"]
    nwb_path = paths["nwb_path"]
    analysis_dir = session_root / source_analysis_folder
    json_paths = sorted(analysis_dir.glob("*.roi_analysis.json"))

    input_rows.append(
        {
            "session": session,
            "nwb_exists": nwb_path.exists(),
            "analysis_dir_exists": analysis_dir.exists(),
            "n_json": len(json_paths),
            "nwb_path": str(nwb_path),
            "analysis_dir": str(analysis_dir),
        }
    )

input_summary = pd.DataFrame(input_rows)
display(input_summary)

missing = input_summary[
    (~input_summary["nwb_exists"])
    | (~input_summary["analysis_dir_exists"])
    | (input_summary["n_json"] == 0)
]

if not missing.empty:
    raise FileNotFoundError("Missing NWB files or analysis JSONs. See input_summary above.")

,session,nwb_exists,analysis_dir_exists,n_json,nwb_path,analysis_dir
0,L1.ST8,True,True,12,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/sub-L1-ST8_ses-20240905T115902.nwb,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/analysis
1,L2.ST8,True,True,7,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/sub-L2-ST8_ses-20240909T100245.nwb,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/analysis
2,L3.ST6,True,True,21,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/sub-L3-ST6_ses-20240909T112846.nwb,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis
3,L4.ST8,True,True,31,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/sub-L4-ST8_ses-20240916T101347.nwb,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis

In [4]:
# Run Reanalysis
run_rows = []

if run_reanalysis:
    for session, paths in session_paths.items():
        session_root = paths["session_root"]
        nwb_path = paths["nwb_path"]
        analysis_dir = session_root / source_analysis_folder
        reanalysis_dir = session_root / reanalysis_folder
        json_paths = sorted(analysis_dir.glob("*.roi_analysis.json"))

        if save_reanalysis:
            reanalysis_dir.mkdir(parents=True, exist_ok=True)

        print(f"{session}: reanalysing {len(json_paths)} fields")

        for json_path in json_paths:
            state, analysis_payload = reconstruct_state_from_saved_analysis(
                nwb_path,
                analysis_path=json_path,
                display_mode=display_mode,
            )

            results, state = RNAscopeAnalysisFinish(state, **new_params)

            out_path = None
            if save_reanalysis:
                out_path = save_rnascope_field_analysis(
                    state,
                    results,
                    analysis_params=new_params,
                    out_dir=reanalysis_dir,
                )

            run_rows.append(
                {
                    "session": session,
                    "field": state["field"],
                    "count_channel": state.get("count_channel"),
                    "n_roi_rows": len(results),
                    "source_json": str(json_path),
                    "reanalysis_json": str(out_path) if out_path is not None else None,
                }
            )

run_summary = pd.DataFrame(run_rows)
display(run_summary)

L1.ST8: reanalysing 12 fields
L2.ST8: reanalysing 7 fields
L3.ST6: reanalysing 21 fields
L4.ST8: reanalysing 31 fields

,session,field,count_channel,n_roi_rows,source_json,reanalysis_json
0,L1.ST8,L1.ST8_C.L_60x.01,s_C004,5,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/analysis/L1.ST8_C.L_60x.01.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/reanalysis/L1.ST8_C.L_60x.01.roi_analysis.json
1,L1.ST8,L1.ST8_C.L_60x.02,s_C004,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/analysis/L1.ST8_C.L_60x.02.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/reanalysis/L1.ST8_C.L_60x.02.roi_analysis.json
2,L1.ST8,L1.ST8_C.L_60x.03,s_C004,7,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/analysis/L1.ST8_C.L_60x.03.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/reanalysis/L1.ST8_C.L_60x.03.roi_analysis.json
3,L1.ST8,L1.ST8_C.L_60x.04,s_C004,5,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/analysis/L1.ST8_C.L_60x.04.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/reanalysis/L1.ST8_C.L_60x.04.roi_analysis.json
4,L1.ST8,L1.ST8_C.L_60x.05,s_C004,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/analysis/L1.ST8_C.L_60x.05.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/reanalysis/L1.ST8_C.L_60x.05.roi_analysis.json
5,L1.ST8,L1.ST8_C.L_60x.06,s_C004,1,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/analysis/L1.ST8_C.L_60x.06.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/reanalysis/L1.ST8_C.L_60x.06.roi_analysis.json
6,L1.ST8,L1.ST8_C.UL_60x.01,s_C004,5,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/analysis/L1.ST8_C.UL_60x.01.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/reanalysis/L1.ST8_C.UL_60x.01.roi_analysis.json
7,L1.ST8,L1.ST8_C.UL_60x.02,s_C004,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/analysis/L1.ST8_C.UL_60x.02.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/reanalysis/L1.ST8_C.UL_60x.02.roi_analysis.json
8,L1.ST8,L1.ST8_C.UL_60x.03,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/analysis/L1.ST8_C.UL_60x.03.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/reanalysis/L1.ST8_C.UL_60x.03.roi_analysis.json
9,L1.ST8,L1.ST8_C.UL_60x.04,s_C004,2,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/analysis/L1.ST8_C.UL_60x.04.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/reanalysis/L1.ST8_C.UL_60x.04.roi_analysis.json
10,L1.ST8,L1.ST8_C.UL_60x.05,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/analysis/L1.ST8_C.UL_60x.05.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/reanalysis/L1.ST8_C.UL_60x.05.roi_analysis.json
11,L1.ST8,L1.ST8_C.UL_60x.06,s_C004,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/analysis/L1.ST8_C.UL_60x.06.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L1-ST8/reanalysis/L1.ST8_C.UL_60x.06.roi_analysis.json
12,L2.ST8,L2.ST8.L_60x01,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/analysis/L2.ST8.L_60x01.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/reanalysis/L2.ST8.L_60x01.roi_analysis.json
13,L2.ST8,L2.ST8.L_60x02,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/analysis/L2.ST8.L_60x02.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/reanalysis/L2.ST8.L_60x02.roi_analysis.json
14,L2.ST8,L2.ST8.L_60x03,s_C004,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/analysis/L2.ST8.L_60x03.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/reanalysis/L2.ST8.L_60x03.roi_analysis.json
15,L2.ST8,L2.ST8.L_60x04,s_C004,1,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/analysis/L2.ST8.L_60x04.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/reanalysis/L2.ST8.L_60x04.roi_analysis.json
16,L2.ST8,L2.ST8.UL_60x01,s_C004,5,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/analysis/L2.ST8.UL_60x01.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/reanalysis/L2.ST8.UL_60x01.roi_analysis.json
17,L2.ST8,L2.ST8.UL_60x02,s_C004,5,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/analysis/L2.ST8.UL_60x02.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/reanalysis/L2.ST8.UL_60x02.roi_analysis.json
18,L2.ST8,L2.ST8.UL_60x03,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/analysis/L2.ST8.UL_60x03.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L2-ST8/reanalysis/L2.ST8.UL_60x03.roi_analysis.json
19,L3.ST6,L3.ST6c.L_60x01,s_C004,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6c.L_60x01.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6c.L_60x01.roi_analysis.json
20,L3.ST6,L3.ST6c.L_60x02,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6c.L_60x02.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6c.L_60x02.roi_analysis.json
21,L3.ST6,L3.ST6c.L_60x03,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6c.L_60x03.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6c.L_60x03.roi_analysis.json
22,L3.ST6,L3.ST6c.L_60x04,s_C004,5,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6c.L_60x04.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6c.L_60x04.roi_analysis.json
23,L3.ST6,L3.ST6c.L_60x05,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6c.L_60x05.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6c.L_60x05.roi_analysis.json
24,L3.ST6,L3.ST6c.L_60x06,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6c.L_60x06.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6c.L_60x06.roi_analysis.json
25,L3.ST6,L3.ST6c.L_60x07,s_C004,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6c.L_60x07.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6c.L_60x07.roi_analysis.json
26,L3.ST6,L3.ST6c.UL_60x01,s_C004,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6c.UL_60x01.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6c.UL_60x01.roi_analysis.json
27,L3.ST6,L3.ST6c.UL_60x02,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6c.UL_60x02.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6c.UL_60x02.roi_analysis.json
28,L3.ST6,L3.ST6c.UL_60x03,s_C004,6,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6c.UL_60x03.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6c.UL_60x03.roi_analysis.json
29,L3.ST6,L3.ST6c.UL_60x04,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6c.UL_60x04.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6c.UL_60x04.roi_analysis.json
30,L3.ST6,L3.ST6d.L_60x01,s_C004,7,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6d.L_60x01.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6d.L_60x01.roi_analysis.json
31,L3.ST6,L3.ST6d.L_60x02,s_C004,5,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6d.L_60x02.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6d.L_60x02.roi_analysis.json
32,L3.ST6,L3.ST6d.L_60x03,s_C004,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6d.L_60x03.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6d.L_60x03.roi_analysis.json
33,L3.ST6,L3.ST6d.L_60x04,s_C004,5,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6d.L_60x04.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6d.L_60x04.roi_analysis.json
34,L3.ST6,L3.ST6d.L_60x05,s_C004,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6d.L_60x05.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6d.L_60x05.roi_analysis.json
35,L3.ST6,L3.ST6d.UL_60x01,s_C004,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6d.UL_60x01.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6d.UL_60x01.roi_analysis.json
36,L3.ST6,L3.ST6d.UL_60x02,s_C004,6,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6d.UL_60x02.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6d.UL_60x02.roi_analysis.json
37,L3.ST6,L3.ST6d.UL_60x03,s_C004,1,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6d.UL_60x03.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6d.UL_60x03.roi_analysis.json
38,L3.ST6,L3.ST6d.UL_60x04,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6d.UL_60x04.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6d.UL_60x04.roi_analysis.json
39,L3.ST6,L3.ST6d.UL_60x05,s_C004,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/analysis/L3.ST6d.UL_60x05.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L3-ST6/reanalysis/L3.ST6d.UL_60x05.roi_analysis.json
40,L4.ST8,L4.ST8.B.L_60x01,s_C003,1,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.L_60x01.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.L_60x01.roi_analysis.json
41,L4.ST8,L4.ST8.B.L_60x02,s_C003,2,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.L_60x02.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.L_60x02.roi_analysis.json
42,L4.ST8,L4.ST8.B.L_60x03,s_C003,2,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.L_60x03.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.L_60x03.roi_analysis.json
43,L4.ST8,L4.ST8.B.L_60x04,s_C003,2,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.L_60x04.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.L_60x04.roi_analysis.json
44,L4.ST8,L4.ST8.B.L_60x05,s_C003,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.L_60x05.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.L_60x05.roi_analysis.json
45,L4.ST8,L4.ST8.B.L_60x06,s_C003,2,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.L_60x06.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.L_60x06.roi_analysis.json
46,L4.ST8,L4.ST8.B.L_60x07,s_C003,1,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.L_60x07.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.L_60x07.roi_analysis.json
47,L4.ST8,L4.ST8.B.UL_60x01,s_C003,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.UL_60x01.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.UL_60x01.roi_analysis.json
48,L4.ST8,L4.ST8.B.UL_60x02,s_C003,2,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.UL_60x02.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.UL_60x02.roi_analysis.json
49,L4.ST8,L4.ST8.B.UL_60x03,s_C003,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.UL_60x03.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.UL_60x03.roi_analysis.json
50,L4.ST8,L4.ST8.B.UL_60x04,s_C003,2,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.UL_60x04.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.UL_60x04.roi_analysis.json
51,L4.ST8,L4.ST8.B.UL_60x05,s_C003,2,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.UL_60x05.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.UL_60x05.roi_analysis.json
52,L4.ST8,L4.ST8.B.UL_60x06,s_C003,1,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.UL_60x06.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.UL_60x06.roi_analysis.json
53,L4.ST8,L4.ST8.B.UL_60x07,s_C003,2,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.UL_60x07.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.UL_60x07.roi_analysis.json
54,L4.ST8,L4.ST8.B.UL_60x08,s_C003,2,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.B.UL_60x08.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.B.UL_60x08.roi_analysis.json
55,L4.ST8,L4.ST8.C.L_60x01,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.C.L_60x01.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.C.L_60x01.roi_analysis.json
56,L4.ST8,L4.ST8.C.L_60x02,s_C004,2,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.C.L_60x02.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.C.L_60x02.roi_analysis.json
57,L4.ST8,L4.ST8.C.L_60x03,s_C004,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.C.L_60x03.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.C.L_60x03.roi_analysis.json
58,L4.ST8,L4.ST8.C.L_60x04,s_C004,5,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.C.L_60x04.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.C.L_60x04.roi_analysis.json
59,L4.ST8,L4.ST8.C.L_60x05,s_C004,5,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.C.L_60x05.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.C.L_60x05.roi_analysis.json
60,L4.ST8,L4.ST8.C.L_60x06,s_C004,5,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.C.L_60x06.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.C.L_60x06.roi_analysis.json
61,L4.ST8,L4.ST8.C.L_60x07,s_C004,5,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.C.L_60x07.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.C.L_60x07.roi_analysis.json
62,L4.ST8,L4.ST8.C.L_60x08,s_C004,5,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.C.L_60x08.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.C.L_60x08.roi_analysis.json
63,L4.ST8,L4.ST8.C.UL_60x01,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.C.UL_60x01.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.C.UL_60x01.roi_analysis.json
64,L4.ST8,L4.ST8.C.UL_60x02,s_C004,6,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.C.UL_60x02.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.C.UL_60x02.roi_analysis.json
65,L4.ST8,L4.ST8.C.UL_60x03,s_C004,2,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.C.UL_60x03.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.C.UL_60x03.roi_analysis.json
66,L4.ST8,L4.ST8.C.UL_60x04,s_C004,3,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.C.UL_60x04.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.C.UL_60x04.roi_analysis.json
67,L4.ST8,L4.ST8.C.UL_60x05,s_C004,4,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/analysis/L4.ST8.C.UL_60x05.roi_analysis.json,/Users/euo9382/Documents/Repositories/analysis_Belal2026/NWBdata/001832/sub-L4-ST8/reanalysis/L4.ST8.C.UL_60x05.roi_analysis.json

In [5]:
# Build Counts DataFrame From Reanalysis JSONs
reanalysis_json_paths = []

for session, paths in session_paths.items():
    reanalysis_dir = paths["session_root"] / reanalysis_folder
    reanalysis_json_paths.extend(sorted(reanalysis_dir.glob("*.roi_analysis.json")))

reanalysis_counts = counts_from_roi_jsons(reanalysis_json_paths)

display(Markdown(f"Reanalysis JSON files: `{len(reanalysis_json_paths)}`"))
display(reanalysis_counts)

Reanalysis JSON files: `71`

,condition,cell_type,slice_id,field,hemisphere,field_index,replicate,count,session,session_group,count_channel,analysis_json
0,Intact,NDNF+,L1.ST8_C,L1.ST8_C.UL_60x.01,UL,1,1,23,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.01.roi_analysis.json
1,Intact,NDNF+,L1.ST8_C,L1.ST8_C.UL_60x.01,UL,1,2,26,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.01.roi_analysis.json
2,Intact,NDNF+,L1.ST8_C,L1.ST8_C.UL_60x.01,UL,1,3,14,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.01.roi_analysis.json
3,Intact,NDNF+,L1.ST8_C,L1.ST8_C.UL_60x.01,UL,1,4,6,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.01.roi_analysis.json
4,Intact,NDNF+,L1.ST8_C,L1.ST8_C.UL_60x.01,UL,1,5,11,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.01.roi_analysis.json
5,Intact,NDNF+,L1.ST8_C,L1.ST8_C.UL_60x.02,UL,2,1,15,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.02.roi_analysis.json
6,Intact,NDNF+,L1.ST8_C,L1.ST8_C.UL_60x.02,UL,2,2,10,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.02.roi_analysis.json
7,Intact,NDNF+,L1.ST8_C,L1.ST8_C.UL_60x.03,UL,3,1,36,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.03.roi_analysis.json
8,Intact,NDNF+,L1.ST8_C,L1.ST8_C.UL_60x.03,UL,3,2,26,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.03.roi_analysis.json
9,Intact,NDNF+,L1.ST8_C,L1.ST8_C.UL_60x.03,UL,3,3,23,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.03.roi_analysis.json
10,Intact,NDNF+,L1.ST8_C,L1.ST8_C.UL_60x.04,UL,4,1,22,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.04.roi_analysis.json
11,Intact,NDNF+,L1.ST8_C,L1.ST8_C.UL_60x.04,UL,4,2,23,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.04.roi_analysis.json
12,Intact,NDNF+,L1.ST8_C,L1.ST8_C.UL_60x.06,UL,6,1,16,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.06.roi_analysis.json
13,Intact,NDNF+,L1.ST8_C,L1.ST8_C.UL_60x.06,UL,6,2,14,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.06.roi_analysis.json
14,Intact,TH+,L1.ST8_C,L1.ST8_C.UL_60x.02,UL,2,1,8,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.02.roi_analysis.json
15,Intact,TH+,L1.ST8_C,L1.ST8_C.UL_60x.03,UL,3,1,3,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.03.roi_analysis.json
16,Intact,TH+,L1.ST8_C,L1.ST8_C.UL_60x.05,UL,5,1,8,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.05.roi_analysis.json
17,Intact,TH+,L1.ST8_C,L1.ST8_C.UL_60x.05,UL,5,2,8,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.05.roi_analysis.json
18,Intact,TH+,L1.ST8_C,L1.ST8_C.UL_60x.05,UL,5,3,5,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.05.roi_analysis.json
19,Intact,TH+,L1.ST8_C,L1.ST8_C.UL_60x.05,UL,5,4,11,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.05.roi_analysis.json
20,Intact,TH+,L1.ST8_C,L1.ST8_C.UL_60x.06,UL,6,1,9,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.UL_60x.06.roi_analysis.json
21,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.01,L,1,1,14,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.01.roi_analysis.json
22,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.01,L,1,2,6,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.01.roi_analysis.json
23,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.01,L,1,3,5,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.01.roi_analysis.json
24,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.01,L,1,4,13,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.01.roi_analysis.json
25,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.01,L,1,5,16,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.01.roi_analysis.json
26,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.02,L,2,1,16,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.02.roi_analysis.json
27,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.02,L,2,2,12,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.02.roi_analysis.json
28,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.02,L,2,3,17,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.02.roi_analysis.json
29,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.03,L,3,1,10,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.03.roi_analysis.json
30,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.03,L,3,2,10,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.03.roi_analysis.json
31,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.03,L,3,3,11,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.03.roi_analysis.json
32,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.03,L,3,4,9,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.03.roi_analysis.json
33,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.03,L,3,5,23,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.03.roi_analysis.json
34,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.04,L,4,1,25,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.04.roi_analysis.json
35,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.04,L,4,2,33,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.04.roi_analysis.json
36,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.05,L,5,1,20,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.05.roi_analysis.json
37,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.05,L,5,2,9,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.05.roi_analysis.json
38,Lesioned,NDNF+,L1.ST8_C,L1.ST8_C.L_60x.06,L,6,1,9,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.06.roi_analysis.json
39,Lesioned,TH+,L1.ST8_C,L1.ST8_C.L_60x.03,L,3,1,4,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.03.roi_analysis.json
40,Lesioned,TH+,L1.ST8_C,L1.ST8_C.L_60x.03,L,3,2,5,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.03.roi_analysis.json
41,Lesioned,TH+,L1.ST8_C,L1.ST8_C.L_60x.04,L,4,1,5,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.04.roi_analysis.json
42,Lesioned,TH+,L1.ST8_C,L1.ST8_C.L_60x.04,L,4,2,3,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.04.roi_analysis.json
43,Lesioned,TH+,L1.ST8_C,L1.ST8_C.L_60x.04,L,4,3,6,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.04.roi_analysis.json
44,Lesioned,TH+,L1.ST8_C,L1.ST8_C.L_60x.05,L,5,1,4,sub-L1-ST8,sub-L1-ST8,s_C004,L1.ST8_C.L_60x.05.roi_analysis.json
45,Intact,NDNF+,L2.ST8,L2.ST8.UL_60x01,UL,1,1,19,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.UL_60x01.roi_analysis.json
46,Intact,NDNF+,L2.ST8,L2.ST8.UL_60x01,UL,1,2,27,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.UL_60x01.roi_analysis.json
47,Intact,NDNF+,L2.ST8,L2.ST8.UL_60x01,UL,1,3,16,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.UL_60x01.roi_analysis.json
48,Intact,NDNF+,L2.ST8,L2.ST8.UL_60x01,UL,1,4,30,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.UL_60x01.roi_analysis.json
49,Intact,NDNF+,L2.ST8,L2.ST8.UL_60x01,UL,1,5,28,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.UL_60x01.roi_analysis.json
50,Intact,NDNF+,L2.ST8,L2.ST8.UL_60x02,UL,2,1,15,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.UL_60x02.roi_analysis.json
51,Intact,NDNF+,L2.ST8,L2.ST8.UL_60x02,UL,2,2,10,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.UL_60x02.roi_analysis.json
52,Intact,NDNF+,L2.ST8,L2.ST8.UL_60x02,UL,2,3,23,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.UL_60x02.roi_analysis.json
53,Intact,NDNF+,L2.ST8,L2.ST8.UL_60x02,UL,2,4,19,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.UL_60x02.roi_analysis.json
54,Intact,NDNF+,L2.ST8,L2.ST8.UL_60x02,UL,2,5,17,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.UL_60x02.roi_analysis.json
55,Intact,NDNF+,L2.ST8,L2.ST8.UL_60x03,UL,3,1,16,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.UL_60x03.roi_analysis.json
56,Intact,NDNF+,L2.ST8,L2.ST8.UL_60x03,UL,3,2,11,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.UL_60x03.roi_analysis.json
57,Intact,NDNF+,L2.ST8,L2.ST8.UL_60x03,UL,3,3,13,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.UL_60x03.roi_analysis.json
58,Intact,TH+,L2.ST8,L2.ST8.UL_60x03,UL,3,1,15,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.UL_60x03.roi_analysis.json
59,Lesioned,NDNF+,L2.ST8,L2.ST8.L_60x01,L,1,1,6,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.L_60x01.roi_analysis.json
60,Lesioned,NDNF+,L2.ST8,L2.ST8.L_60x01,L,1,2,14,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.L_60x01.roi_analysis.json
61,Lesioned,NDNF+,L2.ST8,L2.ST8.L_60x01,L,1,3,26,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.L_60x01.roi_analysis.json
62,Lesioned,NDNF+,L2.ST8,L2.ST8.L_60x01,L,1,4,19,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.L_60x01.roi_analysis.json
63,Lesioned,NDNF+,L2.ST8,L2.ST8.L_60x02,L,2,1,10,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.L_60x02.roi_analysis.json
64,Lesioned,NDNF+,L2.ST8,L2.ST8.L_60x02,L,2,2,7,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.L_60x02.roi_analysis.json
65,Lesioned,NDNF+,L2.ST8,L2.ST8.L_60x02,L,2,3,13,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.L_60x02.roi_analysis.json
66,Lesioned,NDNF+,L2.ST8,L2.ST8.L_60x02,L,2,4,8,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.L_60x02.roi_analysis.json
67,Lesioned,NDNF+,L2.ST8,L2.ST8.L_60x03,L,3,1,7,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.L_60x03.roi_analysis.json
68,Lesioned,NDNF+,L2.ST8,L2.ST8.L_60x03,L,3,2,15,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.L_60x03.roi_analysis.json
69,Lesioned,NDNF+,L2.ST8,L2.ST8.L_60x03,L,3,3,17,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.L_60x03.roi_analysis.json
70,Lesioned,TH+,L2.ST8,L2.ST8.L_60x04,L,4,1,1,sub-L2-ST8,sub-L2-ST8,s_C004,L2.ST8.L_60x04.roi_analysis.json
71,Intact,NDNF+,L3.ST6c,L3.ST6c.UL_60x01,UL,1,1,14,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x01.roi_analysis.json
72,Intact,NDNF+,L3.ST6c,L3.ST6c.UL_60x01,UL,1,2,24,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x01.roi_analysis.json
73,Intact,NDNF+,L3.ST6c,L3.ST6c.UL_60x01,UL,1,3,33,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x01.roi_analysis.json
74,Intact,NDNF+,L3.ST6d,L3.ST6d.UL_60x01,UL,1,1,17,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x01.roi_analysis.json
75,Intact,NDNF+,L3.ST6d,L3.ST6d.UL_60x01,UL,1,2,12,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x01.roi_analysis.json
76,Intact,NDNF+,L3.ST6d,L3.ST6d.UL_60x01,UL,1,3,22,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x01.roi_analysis.json
77,Intact,NDNF+,L3.ST6c,L3.ST6c.UL_60x02,UL,2,1,19,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x02.roi_analysis.json
78,Intact,NDNF+,L3.ST6c,L3.ST6c.UL_60x02,UL,2,2,19,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x02.roi_analysis.json
79,Intact,NDNF+,L3.ST6c,L3.ST6c.UL_60x02,UL,2,3,33,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x02.roi_analysis.json
80,Intact,NDNF+,L3.ST6d,L3.ST6d.UL_60x02,UL,2,1,20,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x02.roi_analysis.json
81,Intact,NDNF+,L3.ST6d,L3.ST6d.UL_60x02,UL,2,2,19,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x02.roi_analysis.json
82,Intact,NDNF+,L3.ST6d,L3.ST6d.UL_60x02,UL,2,3,22,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x02.roi_analysis.json
83,Intact,NDNF+,L3.ST6d,L3.ST6d.UL_60x02,UL,2,4,27,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x02.roi_analysis.json
84,Intact,NDNF+,L3.ST6d,L3.ST6d.UL_60x02,UL,2,5,42,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x02.roi_analysis.json
85,Intact,NDNF+,L3.ST6c,L3.ST6c.UL_60x03,UL,3,1,45,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x03.roi_analysis.json
86,Intact,NDNF+,L3.ST6c,L3.ST6c.UL_60x03,UL,3,2,36,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x03.roi_analysis.json
87,Intact,NDNF+,L3.ST6c,L3.ST6c.UL_60x03,UL,3,3,22,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x03.roi_analysis.json
88,Intact,NDNF+,L3.ST6d,L3.ST6d.UL_60x03,UL,3,1,29,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x03.roi_analysis.json
89,Intact,NDNF+,L3.ST6c,L3.ST6c.UL_60x04,UL,4,1,17,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x04.roi_analysis.json
90,Intact,NDNF+,L3.ST6c,L3.ST6c.UL_60x04,UL,4,2,35,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x04.roi_analysis.json
91,Intact,NDNF+,L3.ST6c,L3.ST6c.UL_60x04,UL,4,3,19,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x04.roi_analysis.json
92,Intact,NDNF+,L3.ST6d,L3.ST6d.UL_60x04,UL,4,1,19,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x04.roi_analysis.json
93,Intact,NDNF+,L3.ST6d,L3.ST6d.UL_60x04,UL,4,2,24,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x04.roi_analysis.json
94,Intact,NDNF+,L3.ST6d,L3.ST6d.UL_60x04,UL,4,3,7,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x04.roi_analysis.json
95,Intact,NDNF+,L3.ST6d,L3.ST6d.UL_60x05,UL,5,1,24,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x05.roi_analysis.json
96,Intact,NDNF+,L3.ST6d,L3.ST6d.UL_60x05,UL,5,2,14,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x05.roi_analysis.json
97,Intact,TH+,L3.ST6c,L3.ST6c.UL_60x02,UL,2,1,9,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x02.roi_analysis.json
98,Intact,TH+,L3.ST6d,L3.ST6d.UL_60x02,UL,2,1,9,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x02.roi_analysis.json
99,Intact,TH+,L3.ST6c,L3.ST6c.UL_60x03,UL,3,1,6,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x03.roi_analysis.json
100,Intact,TH+,L3.ST6c,L3.ST6c.UL_60x03,UL,3,2,10,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x03.roi_analysis.json
101,Intact,TH+,L3.ST6c,L3.ST6c.UL_60x03,UL,3,3,2,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x03.roi_analysis.json
102,Intact,TH+,L3.ST6c,L3.ST6c.UL_60x04,UL,4,1,9,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.UL_60x04.roi_analysis.json
103,Intact,TH+,L3.ST6d,L3.ST6d.UL_60x04,UL,4,1,5,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x04.roi_analysis.json
104,Intact,TH+,L3.ST6d,L3.ST6d.UL_60x05,UL,5,1,5,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.UL_60x05.roi_analysis.json
105,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x01,L,1,1,36,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x01.roi_analysis.json
106,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x01,L,1,2,28,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x01.roi_analysis.json
107,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x01,L,1,1,19,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x01.roi_analysis.json
108,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x01,L,1,2,26,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x01.roi_analysis.json
109,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x01,L,1,3,16,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x01.roi_analysis.json
110,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x01,L,1,4,25,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x01.roi_analysis.json
111,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x02,L,2,1,15,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x02.roi_analysis.json
112,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x02,L,2,2,16,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x02.roi_analysis.json
113,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x02,L,2,3,11,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x02.roi_analysis.json
114,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x02,L,2,4,17,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x02.roi_analysis.json
115,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x02,L,2,1,6,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x02.roi_analysis.json
116,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x02,L,2,2,29,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x02.roi_analysis.json
117,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x02,L,2,3,18,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x02.roi_analysis.json
118,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x02,L,2,4,9,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x02.roi_analysis.json
119,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x03,L,3,1,15,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x03.roi_analysis.json
120,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x03,L,3,2,14,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x03.roi_analysis.json
121,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x03,L,3,3,28,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x03.roi_analysis.json
122,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x03,L,3,4,30,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x03.roi_analysis.json
123,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x03,L,3,1,17,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x03.roi_analysis.json
124,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x03,L,3,2,22,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x03.roi_analysis.json
125,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x03,L,3,3,27,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x03.roi_analysis.json
126,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x04,L,4,1,12,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x04.roi_analysis.json
127,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x04,L,4,2,11,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x04.roi_analysis.json
128,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x04,L,4,3,9,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x04.roi_analysis.json
129,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x04,L,4,4,29,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x04.roi_analysis.json
130,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x04,L,4,1,16,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x04.roi_analysis.json
131,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x04,L,4,2,26,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x04.roi_analysis.json
132,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x04,L,4,3,22,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x04.roi_analysis.json
133,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x04,L,4,4,10,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x04.roi_analysis.json
134,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x05,L,5,1,34,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x05.roi_analysis.json
135,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x05,L,5,2,32,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x05.roi_analysis.json
136,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x05,L,5,3,28,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x05.roi_analysis.json
137,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x05,L,5,4,20,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x05.roi_analysis.json
138,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x05,L,5,1,19,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x05.roi_analysis.json
139,Lesioned,NDNF+,L3.ST6d,L3.ST6d.L_60x05,L,5,2,9,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x05.roi_analysis.json
140,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x06,L,6,1,20,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x06.roi_analysis.json
141,Lesioned,NDNF+,L3.ST6c,L3.ST6c.L_60x07,L,7,1,9,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x07.roi_analysis.json
142,Lesioned,TH+,L3.ST6c,L3.ST6c.L_60x01,L,1,1,8,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x01.roi_analysis.json
143,Lesioned,TH+,L3.ST6d,L3.ST6d.L_60x01,L,1,1,15,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x01.roi_analysis.json
144,Lesioned,TH+,L3.ST6d,L3.ST6d.L_60x01,L,1,2,7,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x01.roi_analysis.json
145,Lesioned,TH+,L3.ST6d,L3.ST6d.L_60x01,L,1,3,8,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x01.roi_analysis.json
146,Lesioned,TH+,L3.ST6d,L3.ST6d.L_60x02,L,2,1,6,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x02.roi_analysis.json
147,Lesioned,TH+,L3.ST6c,L3.ST6c.L_60x04,L,4,1,9,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x04.roi_analysis.json
148,Lesioned,TH+,L3.ST6d,L3.ST6d.L_60x04,L,4,1,5,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x04.roi_analysis.json
149,Lesioned,TH+,L3.ST6d,L3.ST6d.L_60x05,L,5,1,7,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6d.L_60x05.roi_analysis.json
150,Lesioned,TH+,L3.ST6c,L3.ST6c.L_60x06,L,6,1,14,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x06.roi_analysis.json
151,Lesioned,TH+,L3.ST6c,L3.ST6c.L_60x06,L,6,2,2,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x06.roi_analysis.json
152,Lesioned,TH+,L3.ST6c,L3.ST6c.L_60x06,L,6,3,6,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x06.roi_analysis.json
153,Lesioned,TH+,L3.ST6c,L3.ST6c.L_60x07,L,7,1,6,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x07.roi_analysis.json
154,Lesioned,TH+,L3.ST6c,L3.ST6c.L_60x07,L,7,2,4,sub-L3-ST6,sub-L3-ST6,s_C004,L3.ST6c.L_60x07.roi_analysis.json
155,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x01,UL,1,1,30,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x01.roi_analysis.json
156,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x01,UL,1,2,35,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x01.roi_analysis.json
157,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x01,UL,1,3,46,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x01.roi_analysis.json
158,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x02,UL,2,1,13,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x02.roi_analysis.json
159,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x02,UL,2,2,17,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x02.roi_analysis.json
160,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x02,UL,2,3,23,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x02.roi_analysis.json
161,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x02,UL,2,4,25,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x02.roi_analysis.json
162,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x02,UL,2,5,20,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x02.roi_analysis.json
163,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x03,UL,3,1,45,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x03.roi_analysis.json
164,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x04,UL,4,1,20,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x04.roi_analysis.json
165,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x04,UL,4,2,23,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x04.roi_analysis.json
166,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x05,UL,5,1,22,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x05.roi_analysis.json
167,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x05,UL,5,2,9,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x05.roi_analysis.json
168,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x06,UL,6,1,33,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x06.roi_analysis.json
169,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x07,UL,7,1,18,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x07.roi_analysis.json
170,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x07,UL,7,2,33,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x07.roi_analysis.json
171,Intact,NDNF+,L4.ST8.C,L4.ST8.C.UL_60x07,UL,7,3,15,sub-L4-ST8,sub-L4-ST8,s_C004,L4.ST8.C.UL_60x07.roi_analysis.json

## Load Experimenter Counts From NWB

In [ ]:
experimenter_dfs = []

for session, paths in session_paths.items():
    nwb_path = paths["nwb_path"]

    with NWBHDF5IO(str(nwb_path), "r", load_namespaces=True) as io:
        nwbfile = io.read()
        df = (
            nwbfile.processing["rnascope_analysis_metadata"]["experimenter_chrnb2_counts"]
            .to_dataframe()
            .reset_index(drop=True)
        )

    df["session"] = df["session"] if "session" in df.columns else session
    df["session_group"] = df["session_group"] if "session_group" in df.columns else session
    experimenter_dfs.append(df)

experimenter_counts = pd.concat(experimenter_dfs, ignore_index=True)
experimenter_counts["field_index"] = experimenter_counts["field_index"].astype(int)
experimenter_counts["replicate"] = experimenter_counts["replicate"].astype(int)
experimenter_counts["count"] = experimenter_counts["count"].astype(int)

display(experimenter_counts)

In [ ]:
# Compare Reanalysis Counts With Experimenter Counts

session_name_map = {
    "sub-L1-ST8": "L1.ST8",
    "sub-L2-ST8": "L2.ST8",
    "sub-L3-ST6": "L3.ST6",
    "sub-L4-ST8": "L4.ST8",
}

reanalysis_counts["session"] = reanalysis_counts["session"].replace(session_name_map)
reanalysis_counts["session_group"] = reanalysis_counts["session_group"].replace(session_name_map)

compare_keys = [
    "condition",
    "cell_type",
    "slice_id",
    "field",
    "hemisphere",
    "field_index",
    "replicate",
    "session",
    "session_group",
]

exact_compare = experimenter_counts[compare_keys + ["count"]].merge(
    reanalysis_counts[compare_keys + ["count", "count_channel"]],
    on=compare_keys,
    how="outer",
    suffixes=("_experimenter", "_reanalysis"),
    indicator=True,
)

exact_compare["count_delta"] = exact_compare["count_reanalysis"] - exact_compare["count_experimenter"]

display(Markdown("### Exact ROI/replicate comparison"))
display(exact_compare)

display(Markdown("### Merge status"))
display(exact_compare["_merge"].value_counts(dropna=False).rename_axis("merge_status").reset_index(name="n"))

matched = exact_compare[exact_compare["_merge"] == "both"].copy()
if not matched.empty:
    pearson_r = matched["count_experimenter"].corr(matched["count_reanalysis"], method="pearson")
    spearman_r = matched["count_experimenter"].corr(matched["count_reanalysis"], method="spearman")
    print("matched ROI rows:", len(matched))
    print("Pearson r:", round(pearson_r, 4))
    print("Spearman r:", round(spearman_r, 4))
    print("mean delta:", round(matched["count_delta"].mean(), 4))
    print("median delta:", round(matched["count_delta"].median(), 4))

In [ ]:
# Field-Level Mean Comparison

field_keys = [
    "condition",
    "cell_type",
    "slice_id",
    "field",
    "hemisphere",
    "field_index",
    "session",
    "session_group",
]

experimenter_field = (
    experimenter_counts
    .groupby(field_keys, as_index=False)["count"]
    .mean()
    .rename(columns={"count": "experimenter_mean"})
)

reanalysis_field = (
    reanalysis_counts
    .groupby(field_keys, as_index=False)["count"]
    .mean()
    .rename(columns={"count": "reanalysis_mean"})
)

field_compare = experimenter_field.merge(
    reanalysis_field,
    on=field_keys,
    how="outer",
    indicator=True,
)
field_compare["mean_delta"] = field_compare["reanalysis_mean"] - field_compare["experimenter_mean"]

display(field_compare)

matched_field = field_compare[field_compare["_merge"] == "both"].copy()
if not matched_field.empty:
    pearson_r = matched_field["experimenter_mean"].corr(matched_field["reanalysis_mean"], method="pearson")
    spearman_r = matched_field["experimenter_mean"].corr(matched_field["reanalysis_mean"], method="spearman")
    print("matched field rows:", len(matched_field))
    print("Pearson r:", round(pearson_r, 4))
    print("Spearman r:", round(spearman_r, 4))

In [ ]:
# Optional CSV Export
save_csv = False

if save_csv:
    counts_csv = nwb_root / "rnascope_reanalysis_counts.csv"
    exact_compare_csv = nwb_root / "rnascope_reanalysis_vs_experimenter_exact.csv"
    field_compare_csv = nwb_root / "rnascope_reanalysis_vs_experimenter_field_means.csv"

    reanalysis_counts.to_csv(counts_csv, index=False)
    exact_compare.to_csv(exact_compare_csv, index=False)
    field_compare.to_csv(field_compare_csv, index=False)

    print(counts_csv)
    print(exact_compare_csv)
    print(field_compare_csv)